using System.Diagnostics;
using System.Drawing;
using System.Windows.Forms;

namespace DBZ_LotSS_Editor
{
    [Microsoft.VisualBasic.CompilerServices.DesignerGenerated()]
    public partial class Data_Groups : HexTools.HexUserControl
    {

        // Form overrides dispose to clean up the component list.
        [DebuggerNonUserCode()]
        protected override void Dispose(bool disposing)
        {
            try
            {
                if (disposing && components != null)
                {
                    components.Dispose();
                }
            }
            finally
            {
                base.Dispose(disposing);
            }
        }

        // Required by the Windows Form Designer
        private System.ComponentModel.IContainer components;

        // NOTE: The following procedure is required by the Windows Form Designer
        // It can be modified using the Windows Form Designer.  
        // Do not modify it using the code editor.
        [DebuggerStepThrough()]
        private void InitializeComponent()
        {
            HexTools.HexListBoxItem hexListBoxItem1 = new HexTools.HexListBoxItem();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Data_Groups));
            HexTools.HexListBoxItem hexListBoxItem2 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem3 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem4 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem5 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem6 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem7 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem8 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem9 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem10 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem11 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem12 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem13 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem14 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem15 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem16 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem17 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem18 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem19 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem20 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem21 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem22 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem23 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem24 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem25 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem26 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem27 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem28 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem29 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem30 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem31 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem32 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem33 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem34 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem35 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem36 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem37 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem38 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem39 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem40 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem41 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem42 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem43 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem44 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem45 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem46 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem47 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem48 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem49 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem50 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem51 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem52 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem53 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem54 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem55 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem56 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem57 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem58 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem59 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem60 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem61 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem62 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem63 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem64 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem65 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem66 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem67 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem68 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem69 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem70 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem71 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem72 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem73 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem74 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem75 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem76 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem77 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem78 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem79 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem80 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem81 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem82 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem83 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem84 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem85 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem86 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem87 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem88 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem89 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem90 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem91 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem92 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem93 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem94 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem95 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem96 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem97 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem98 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem99 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem100 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem101 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem102 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem103 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem104 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem105 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem106 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem107 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem108 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem109 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem110 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem111 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem112 = new HexTools.HexListBoxItem();
            this.HexListBox1 = new HexTools.HexListBox();
            this.BasicListBoxAssociate1 = new BasicTools.BasicControls.BasicListBoxAssociate();
            this.HexPanel1 = new HexTools.HexPanel();
            this.Battler5 = new HexTools.HexComboBox();
            this.Battler4 = new HexTools.HexComboBox();
            this.Battler3 = new HexTools.HexComboBox();
            this.Battler2 = new HexTools.HexComboBox();
            this.Battler1 = new HexTools.HexComboBox();
            this.Label5 = new System.Windows.Forms.Label();
            this.Label1 = new System.Windows.Forms.Label();
            this.Label4 = new System.Windows.Forms.Label();
            this.Label2 = new System.Windows.Forms.Label();
            this.Label3 = new System.Windows.Forms.Label();
            this.BasicListBoxAssociate1.SuspendLayout();
            this.HexPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // HexListBox1
            // 
            this.HexListBox1.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.HexListBox1.FormatString = "X2";
            this.HexListBox1.FormattingEnabled = true;
            this.HexListBox1.IndexDisplay = true;
            hexListBoxItem1.HexOffset = null;
            hexListBoxItem1.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem1.Strings")));
            hexListBoxItem1.Text = "Earth 1 Easy A";
            hexListBoxItem2.HexOffset = null;
            hexListBoxItem2.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem2.Strings")));
            hexListBoxItem2.Text = "Earth 1 Medium A";
            hexListBoxItem3.HexOffset = null;
            hexListBoxItem3.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem3.Strings")));
            hexListBoxItem3.Text = "Earth 1 Hard A";
            hexListBoxItem4.HexOffset = null;
            hexListBoxItem4.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem4.Strings")));
            hexListBoxItem4.Text = "Earth 1 Medium B";
            hexListBoxItem5.HexOffset = null;
            hexListBoxItem5.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem5.Strings")));
            hexListBoxItem5.Text = "Earth 1 Hard B";
            hexListBoxItem6.HexOffset = null;
            hexListBoxItem6.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem6.Strings")));
            hexListBoxItem6.Text = "Earth 1 Boss B";
            hexListBoxItem7.HexOffset = null;
            hexListBoxItem7.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem7.Strings")));
            hexListBoxItem7.Text = "Otherworld Boss C";
            hexListBoxItem8.HexOffset = null;
            hexListBoxItem8.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem8.Strings")));
            hexListBoxItem8.Text = "Earth 1 Boss B";
            hexListBoxItem9.HexOffset = null;
            hexListBoxItem9.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem9.Strings")));
            hexListBoxItem9.Text = "Index08";
            hexListBoxItem10.HexOffset = null;
            hexListBoxItem10.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem10.Strings")));
            hexListBoxItem10.Text = "Index09";
            hexListBoxItem11.HexOffset = null;
            hexListBoxItem11.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem11.Strings")));
            hexListBoxItem11.Text = "Index10";
            hexListBoxItem12.HexOffset = null;
            hexListBoxItem12.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem12.Strings")));
            hexListBoxItem12.Text = "Index11";
            hexListBoxItem13.HexOffset = null;
            hexListBoxItem13.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem13.Strings")));
            hexListBoxItem13.Text = "Index12";
            hexListBoxItem14.HexOffset = null;
            hexListBoxItem14.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem14.Strings")));
            hexListBoxItem14.Text = "Index13";
            hexListBoxItem15.HexOffset = null;
            hexListBoxItem15.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem15.Strings")));
            hexListBoxItem15.Text = "Index14";
            hexListBoxItem16.HexOffset = null;
            hexListBoxItem16.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem16.Strings")));
            hexListBoxItem16.Text = "Index15";
            hexListBoxItem17.HexOffset = null;
            hexListBoxItem17.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem17.Strings")));
            hexListBoxItem17.Text = "Index16";
            hexListBoxItem18.HexOffset = null;
            hexListBoxItem18.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem18.Strings")));
            hexListBoxItem18.Text = "Index17";
            hexListBoxItem19.HexOffset = null;
            hexListBoxItem19.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem19.Strings")));
            hexListBoxItem19.Text = "Earth 2 Boss A";
            hexListBoxItem20.HexOffset = null;
            hexListBoxItem20.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem20.Strings")));
            hexListBoxItem20.Text = "Earth 2 Boss B";
            hexListBoxItem21.HexOffset = null;
            hexListBoxItem21.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem21.Strings")));
            hexListBoxItem21.Text = "Earth 2 Boss C";
            hexListBoxItem22.HexOffset = null;
            hexListBoxItem22.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem22.Strings")));
            hexListBoxItem22.Text = "Earth 2 Boss D";
            hexListBoxItem23.HexOffset = null;
            hexListBoxItem23.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem23.Strings")));
            hexListBoxItem23.Text = "Index22";
            hexListBoxItem24.HexOffset = null;
            hexListBoxItem24.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem24.Strings")));
            hexListBoxItem24.Text = "Index23";
            hexListBoxItem25.HexOffset = null;
            hexListBoxItem25.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem25.Strings")));
            hexListBoxItem25.Text = "Index24";
            hexListBoxItem26.HexOffset = null;
            hexListBoxItem26.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem26.Strings")));
            hexListBoxItem26.Text = "Index25";
            hexListBoxItem27.HexOffset = null;
            hexListBoxItem27.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem27.Strings")));
            hexListBoxItem27.Text = "Otherworld Boss A";
            hexListBoxItem28.HexOffset = null;
            hexListBoxItem28.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem28.Strings")));
            hexListBoxItem28.Text = "Otherworld Boss B";
            hexListBoxItem29.HexOffset = null;
            hexListBoxItem29.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem29.Strings")));
            hexListBoxItem29.Text = "Unused";
            hexListBoxItem30.HexOffset = null;
            hexListBoxItem30.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem30.Strings")));
            hexListBoxItem30.Text = "Earth 2 Training";
            hexListBoxItem31.HexOffset = null;
            hexListBoxItem31.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem31.Strings")));
            hexListBoxItem31.Text = "Index30";
            hexListBoxItem32.HexOffset = null;
            hexListBoxItem32.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem32.Strings")));
            hexListBoxItem32.Text = "Index31";
            hexListBoxItem33.HexOffset = null;
            hexListBoxItem33.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem33.Strings")));
            hexListBoxItem33.Text = "Index32";
            hexListBoxItem34.HexOffset = null;
            hexListBoxItem34.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem34.Strings")));
            hexListBoxItem34.Text = "Index33";
            hexListBoxItem35.HexOffset = null;
            hexListBoxItem35.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem35.Strings")));
            hexListBoxItem35.Text = "Index34";
            hexListBoxItem36.HexOffset = null;
            hexListBoxItem36.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem36.Strings")));
            hexListBoxItem36.Text = "Index35";
            hexListBoxItem37.HexOffset = null;
            hexListBoxItem37.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem37.Strings")));
            hexListBoxItem37.Text = "Namek Boss A";
            hexListBoxItem38.HexOffset = null;
            hexListBoxItem38.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem38.Strings")));
            hexListBoxItem38.Text = "Namek Boss B";
            hexListBoxItem39.HexOffset = null;
            hexListBoxItem39.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem39.Strings")));
            hexListBoxItem39.Text = "Namek Training A";
            hexListBoxItem40.HexOffset = null;
            hexListBoxItem40.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem40.Strings")));
            hexListBoxItem40.Text = "Index39";
            hexListBoxItem41.HexOffset = null;
            hexListBoxItem41.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem41.Strings")));
            hexListBoxItem41.Text = "Index40";
            hexListBoxItem42.HexOffset = null;
            hexListBoxItem42.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem42.Strings")));
            hexListBoxItem42.Text = "Index41";
            hexListBoxItem43.HexOffset = null;
            hexListBoxItem43.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem43.Strings")));
            hexListBoxItem43.Text = "Index42";
            hexListBoxItem44.HexOffset = null;
            hexListBoxItem44.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem44.Strings")));
            hexListBoxItem44.Text = "Index43";
            hexListBoxItem45.HexOffset = null;
            hexListBoxItem45.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem45.Strings")));
            hexListBoxItem45.Text = "Index44";
            hexListBoxItem46.HexOffset = null;
            hexListBoxItem46.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem46.Strings")));
            hexListBoxItem46.Text = "Index45";
            hexListBoxItem47.HexOffset = null;
            hexListBoxItem47.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem47.Strings")));
            hexListBoxItem47.Text = "Index46";
            hexListBoxItem48.HexOffset = null;
            hexListBoxItem48.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem48.Strings")));
            hexListBoxItem48.Text = "Index47";
            hexListBoxItem49.HexOffset = null;
            hexListBoxItem49.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem49.Strings")));
            hexListBoxItem49.Text = "Index48";
            hexListBoxItem50.HexOffset = null;
            hexListBoxItem50.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem50.Strings")));
            hexListBoxItem50.Text = "Index49";
            hexListBoxItem51.HexOffset = null;
            hexListBoxItem51.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem51.Strings")));
            hexListBoxItem51.Text = "Index50";
            hexListBoxItem52.HexOffset = null;
            hexListBoxItem52.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem52.Strings")));
            hexListBoxItem52.Text = "Index51";
            hexListBoxItem53.HexOffset = null;
            hexListBoxItem53.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem53.Strings")));
            hexListBoxItem53.Text = "Index52";
            hexListBoxItem54.HexOffset = null;
            hexListBoxItem54.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem54.Strings")));
            hexListBoxItem54.Text = "Index53";
            hexListBoxItem55.HexOffset = null;
            hexListBoxItem55.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem55.Strings")));
            hexListBoxItem55.Text = "Index54";
            hexListBoxItem56.HexOffset = null;
            hexListBoxItem56.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem56.Strings")));
            hexListBoxItem56.Text = "Index55";
            hexListBoxItem57.HexOffset = null;
            hexListBoxItem57.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem57.Strings")));
            hexListBoxItem57.Text = "Namek Boss C";
            hexListBoxItem58.HexOffset = null;
            hexListBoxItem58.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem58.Strings")));
            hexListBoxItem58.Text = "Namek Boss D";
            hexListBoxItem59.HexOffset = null;
            hexListBoxItem59.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem59.Strings")));
            hexListBoxItem59.Text = "Index58";
            hexListBoxItem60.HexOffset = null;
            hexListBoxItem60.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem60.Strings")));
            hexListBoxItem60.Text = "Index59";
            hexListBoxItem61.HexOffset = null;
            hexListBoxItem61.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem61.Strings")));
            hexListBoxItem61.Text = "Index60";
            hexListBoxItem62.HexOffset = null;
            hexListBoxItem62.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem62.Strings")));
            hexListBoxItem62.Text = "Index61";
            hexListBoxItem63.HexOffset = null;
            hexListBoxItem63.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem63.Strings")));
            hexListBoxItem63.Text = "Index62";
            hexListBoxItem64.HexOffset = null;
            hexListBoxItem64.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem64.Strings")));
            hexListBoxItem64.Text = "Index63";
            hexListBoxItem65.HexOffset = null;
            hexListBoxItem65.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem65.Strings")));
            hexListBoxItem65.Text = "Index64";
            hexListBoxItem66.HexOffset = null;
            hexListBoxItem66.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem66.Strings")));
            hexListBoxItem66.Text = "Index65";
            hexListBoxItem67.HexOffset = null;
            hexListBoxItem67.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem67.Strings")));
            hexListBoxItem67.Text = "Index66";
            hexListBoxItem68.HexOffset = null;
            hexListBoxItem68.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem68.Strings")));
            hexListBoxItem68.Text = "Index67";
            hexListBoxItem69.HexOffset = null;
            hexListBoxItem69.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem69.Strings")));
            hexListBoxItem69.Text = "Index68";
            hexListBoxItem70.HexOffset = null;
            hexListBoxItem70.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem70.Strings")));
            hexListBoxItem70.Text = "Index69";
            hexListBoxItem71.HexOffset = null;
            hexListBoxItem71.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem71.Strings")));
            hexListBoxItem71.Text = "Index70";
            hexListBoxItem72.HexOffset = null;
            hexListBoxItem72.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem72.Strings")));
            hexListBoxItem72.Text = "Index71";
            hexListBoxItem73.HexOffset = null;
            hexListBoxItem73.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem73.Strings")));
            hexListBoxItem73.Text = "Index72";
            hexListBoxItem74.HexOffset = null;
            hexListBoxItem74.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem74.Strings")));
            hexListBoxItem74.Text = "Index73";
            hexListBoxItem75.HexOffset = null;
            hexListBoxItem75.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem75.Strings")));
            hexListBoxItem75.Text = "Index74";
            hexListBoxItem76.HexOffset = null;
            hexListBoxItem76.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem76.Strings")));
            hexListBoxItem76.Text = "Index75";
            hexListBoxItem77.HexOffset = null;
            hexListBoxItem77.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem77.Strings")));
            hexListBoxItem77.Text = "Index76";
            hexListBoxItem78.HexOffset = null;
            hexListBoxItem78.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem78.Strings")));
            hexListBoxItem78.Text = "Namek Boss E";
            hexListBoxItem79.HexOffset = null;
            hexListBoxItem79.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem79.Strings")));
            hexListBoxItem79.Text = "Namek Boss F";
            hexListBoxItem80.HexOffset = null;
            hexListBoxItem80.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem80.Strings")));
            hexListBoxItem80.Text = "Namek Boss G1";
            hexListBoxItem81.HexOffset = null;
            hexListBoxItem81.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem81.Strings")));
            hexListBoxItem81.Text = "Namek Boss G2";
            hexListBoxItem82.HexOffset = null;
            hexListBoxItem82.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem82.Strings")));
            hexListBoxItem82.Text = "Namek Boss H";
            hexListBoxItem83.HexOffset = null;
            hexListBoxItem83.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem83.Strings")));
            hexListBoxItem83.Text = "Otherworld Boss D";
            hexListBoxItem84.HexOffset = null;
            hexListBoxItem84.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem84.Strings")));
            hexListBoxItem84.Text = "Namek Boss K";
            hexListBoxItem85.HexOffset = null;
            hexListBoxItem85.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem85.Strings")));
            hexListBoxItem85.Text = "Namek Boss L";
            hexListBoxItem86.HexOffset = null;
            hexListBoxItem86.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem86.Strings")));
            hexListBoxItem86.Text = "Namek Boss M2";
            hexListBoxItem87.HexOffset = null;
            hexListBoxItem87.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem87.Strings")));
            hexListBoxItem87.Text = "Namek Final Boss B";
            hexListBoxItem88.HexOffset = null;
            hexListBoxItem88.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem88.Strings")));
            hexListBoxItem88.Text = "Namek Boss I";
            hexListBoxItem89.HexOffset = null;
            hexListBoxItem89.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem89.Strings")));
            hexListBoxItem89.Text = "Namek Boss J";
            hexListBoxItem90.HexOffset = null;
            hexListBoxItem90.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem90.Strings")));
            hexListBoxItem90.Text = "Namek Boss M1";
            hexListBoxItem91.HexOffset = null;
            hexListBoxItem91.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem91.Strings")));
            hexListBoxItem91.Text = "Index90";
            hexListBoxItem92.HexOffset = null;
            hexListBoxItem92.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem92.Strings")));
            hexListBoxItem92.Text = "Ship Training A";
            hexListBoxItem93.HexOffset = null;
            hexListBoxItem93.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem93.Strings")));
            hexListBoxItem93.Text = "Ship Training B";
            hexListBoxItem94.HexOffset = null;
            hexListBoxItem94.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem94.Strings")));
            hexListBoxItem94.Text = "Ship Training C";
            hexListBoxItem95.HexOffset = null;
            hexListBoxItem95.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem95.Strings")));
            hexListBoxItem95.Text = "Ship Training D";
            hexListBoxItem96.HexOffset = null;
            hexListBoxItem96.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem96.Strings")));
            hexListBoxItem96.Text = "Ship Training E";
            hexListBoxItem97.HexOffset = null;
            hexListBoxItem97.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem97.Strings")));
            hexListBoxItem97.Text = "Ship Training F";
            hexListBoxItem98.HexOffset = null;
            hexListBoxItem98.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem98.Strings")));
            hexListBoxItem98.Text = "Ship Training G";
            hexListBoxItem99.HexOffset = null;
            hexListBoxItem99.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem99.Strings")));
            hexListBoxItem99.Text = "Ship Training H";
            hexListBoxItem100.HexOffset = null;
            hexListBoxItem100.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem100.Strings")));
            hexListBoxItem100.Text = "Ship Training I";
            hexListBoxItem101.HexOffset = null;
            hexListBoxItem101.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem101.Strings")));
            hexListBoxItem101.Text = "Ship Training J";
            hexListBoxItem102.HexOffset = null;
            hexListBoxItem102.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem102.Strings")));
            hexListBoxItem102.Text = "Index101";
            hexListBoxItem103.HexOffset = null;
            hexListBoxItem103.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem103.Strings")));
            hexListBoxItem103.Text = "Index102";
            hexListBoxItem104.HexOffset = null;
            hexListBoxItem104.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem104.Strings")));
            hexListBoxItem104.Text = "Index103";
            hexListBoxItem105.HexOffset = null;
            hexListBoxItem105.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem105.Strings")));
            hexListBoxItem105.Text = "Namek Boss G3";
            hexListBoxItem106.HexOffset = null;
            hexListBoxItem106.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem106.Strings")));
            hexListBoxItem106.Text = "Namek Boss G4";
            hexListBoxItem107.HexOffset = null;
            hexListBoxItem107.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem107.Strings")));
            hexListBoxItem107.Text = "Index106";
            hexListBoxItem108.HexOffset = null;
            hexListBoxItem108.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem108.Strings")));
            hexListBoxItem108.Text = "Index107";
            hexListBoxItem109.HexOffset = null;
            hexListBoxItem109.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem109.Strings")));
            hexListBoxItem109.Text = "Index108";
            hexListBoxItem110.HexOffset = null;
            hexListBoxItem110.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem110.Strings")));
            hexListBoxItem110.Text = "Namek Training B";
            hexListBoxItem111.HexOffset = null;
            hexListBoxItem111.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem111.Strings")));
            hexListBoxItem111.Text = "Namek Final Boss A";
            hexListBoxItem112.HexOffset = null;
            hexListBoxItem112.Strings = ((System.Collections.Specialized.StringCollection)(resources.GetObject("hexListBoxItem112.Strings")));
            hexListBoxItem112.Text = "Namek Secret Boss";
            this.HexListBox1.Items.Add(hexListBoxItem1);
            this.HexListBox1.Items.Add(hexListBoxItem2);
            this.HexListBox1.Items.Add(hexListBoxItem3);
            this.HexListBox1.Items.Add(hexListBoxItem4);
            this.HexListBox1.Items.Add(hexListBoxItem5);
            this.HexListBox1.Items.Add(hexListBoxItem6);
            this.HexListBox1.Items.Add(hexListBoxItem7);
            this.HexListBox1.Items.Add(hexListBoxItem8);
            this.HexListBox1.Items.Add(hexListBoxItem9);
            this.HexListBox1.Items.Add(hexListBoxItem10);
            this.HexListBox1.Items.Add(hexListBoxItem11);
            this.HexListBox1.Items.Add(hexListBoxItem12);
            this.HexListBox1.Items.Add(hexListBoxItem13);
            this.HexListBox1.Items.Add(hexListBoxItem14);
            this.HexListBox1.Items.Add(hexListBoxItem15);
            this.HexListBox1.Items.Add(hexListBoxItem16);
            this.HexListBox1.Items.Add(hexListBoxItem17);
            this.HexListBox1.Items.Add(hexListBoxItem18);
            this.HexListBox1.Items.Add(hexListBoxItem19);
            this.HexListBox1.Items.Add(hexListBoxItem20);
            this.HexListBox1.Items.Add(hexListBoxItem21);
            this.HexListBox1.Items.Add(hexListBoxItem22);
            this.HexListBox1.Items.Add(hexListBoxItem23);
            this.HexListBox1.Items.Add(hexListBoxItem24);
            this.HexListBox1.Items.Add(hexListBoxItem25);
            this.HexListBox1.Items.Add(hexListBoxItem26);
            this.HexListBox1.Items.Add(hexListBoxItem27);
            this.HexListBox1.Items.Add(hexListBoxItem28);
            this.HexListBox1.Items.Add(hexListBoxItem29);
            this.HexListBox1.Items.Add(hexListBoxItem30);
            this.HexListBox1.Items.Add(hexListBoxItem31);
            this.HexListBox1.Items.Add(hexListBoxItem32);
            this.HexListBox1.Items.Add(hexListBoxItem33);
            this.HexListBox1.Items.Add(hexListBoxItem34);
            this.HexListBox1.Items.Add(hexListBoxItem35);
            this.HexListBox1.Items.Add(hexListBoxItem36);
            this.HexListBox1.Items.Add(hexListBoxItem37);
            this.HexListBox1.Items.Add(hexListBoxItem38);
            this.HexListBox1.Items.Add(hexListBoxItem39);
            this.HexListBox1.Items.Add(hexListBoxItem40);
            this.HexListBox1.Items.Add(hexListBoxItem41);
            this.HexListBox1.Items.Add(hexListBoxItem42);
            this.HexListBox1.Items.Add(hexListBoxItem43);
            this.HexListBox1.Items.Add(hexListBoxItem44);
            this.HexListBox1.Items.Add(hexListBoxItem45);
            this.HexListBox1.Items.Add(hexListBoxItem46);
            this.HexListBox1.Items.Add(hexListBoxItem47);
            this.HexListBox1.Items.Add(hexListBoxItem48);
            this.HexListBox1.Items.Add(hexListBoxItem49);
            this.HexListBox1.Items.Add(hexListBoxItem50);
            this.HexListBox1.Items.Add(hexListBoxItem51);
            this.HexListBox1.Items.Add(hexListBoxItem52);
            this.HexListBox1.Items.Add(hexListBoxItem53);
            this.HexListBox1.Items.Add(hexListBoxItem54);
            this.HexListBox1.Items.Add(hexListBoxItem55);
            this.HexListBox1.Items.Add(hexListBoxItem56);
            this.HexListBox1.Items.Add(hexListBoxItem57);
            this.HexListBox1.Items.Add(hexListBoxItem58);
            this.HexListBox1.Items.Add(hexListBoxItem59);
            this.HexListBox1.Items.Add(hexListBoxItem60);
            this.HexListBox1.Items.Add(hexListBoxItem61);
            this.HexListBox1.Items.Add(hexListBoxItem62);
            this.HexListBox1.Items.Add(hexListBoxItem63);
            this.HexListBox1.Items.Add(hexListBoxItem64);
            this.HexListBox1.Items.Add(hexListBoxItem65);
            this.HexListBox1.Items.Add(hexListBoxItem66);
            this.HexListBox1.Items.Add(hexListBoxItem67);
            this.HexListBox1.Items.Add(hexListBoxItem68);
            this.HexListBox1.Items.Add(hexListBoxItem69);
            this.HexListBox1.Items.Add(hexListBoxItem70);
            this.HexListBox1.Items.Add(hexListBoxItem71);
            this.HexListBox1.Items.Add(hexListBoxItem72);
            this.HexListBox1.Items.Add(hexListBoxItem73);
            this.HexListBox1.Items.Add(hexListBoxItem74);
            this.HexListBox1.Items.Add(hexListBoxItem75);
            this.HexListBox1.Items.Add(hexListBoxItem76);
            this.HexListBox1.Items.Add(hexListBoxItem77);
            this.HexListBox1.Items.Add(hexListBoxItem78);
            this.HexListBox1.Items.Add(hexListBoxItem79);
            this.HexListBox1.Items.Add(hexListBoxItem80);
            this.HexListBox1.Items.Add(hexListBoxItem81);
            this.HexListBox1.Items.Add(hexListBoxItem82);
            this.HexListBox1.Items.Add(hexListBoxItem83);
            this.HexListBox1.Items.Add(hexListBoxItem84);
            this.HexListBox1.Items.Add(hexListBoxItem85);
            this.HexListBox1.Items.Add(hexListBoxItem86);
            this.HexListBox1.Items.Add(hexListBoxItem87);
            this.HexListBox1.Items.Add(hexListBoxItem88);
            this.HexListBox1.Items.Add(hexListBoxItem89);
            this.HexListBox1.Items.Add(hexListBoxItem90);
            this.HexListBox1.Items.Add(hexListBoxItem91);
            this.HexListBox1.Items.Add(hexListBoxItem92);
            this.HexListBox1.Items.Add(hexListBoxItem93);
            this.HexListBox1.Items.Add(hexListBoxItem94);
            this.HexListBox1.Items.Add(hexListBoxItem95);
            this.HexListBox1.Items.Add(hexListBoxItem96);
            this.HexListBox1.Items.Add(hexListBoxItem97);
            this.HexListBox1.Items.Add(hexListBoxItem98);
            this.HexListBox1.Items.Add(hexListBoxItem99);
            this.HexListBox1.Items.Add(hexListBoxItem100);
            this.HexListBox1.Items.Add(hexListBoxItem101);
            this.HexListBox1.Items.Add(hexListBoxItem102);
            this.HexListBox1.Items.Add(hexListBoxItem103);
            this.HexListBox1.Items.Add(hexListBoxItem104);
            this.HexListBox1.Items.Add(hexListBoxItem105);
            this.HexListBox1.Items.Add(hexListBoxItem106);
            this.HexListBox1.Items.Add(hexListBoxItem107);
            this.HexListBox1.Items.Add(hexListBoxItem108);
            this.HexListBox1.Items.Add(hexListBoxItem109);
            this.HexListBox1.Items.Add(hexListBoxItem110);
            this.HexListBox1.Items.Add(hexListBoxItem111);
            this.HexListBox1.Items.Add(hexListBoxItem112);
            this.HexListBox1.Location = new System.Drawing.Point(16, 17);
            this.HexListBox1.Margin = new System.Windows.Forms.Padding(4);
            this.HexListBox1.Name = "HexListBox1";
            this.HexListBox1.SelectedItem = hexListBoxItem1;
            this.HexListBox1.Size = new System.Drawing.Size(232, 550);
            this.HexListBox1.TabIndex = 14;
            // 
            // BasicListBoxAssociate1
            // 
            this.BasicListBoxAssociate1.Controls.Add(this.HexPanel1);
            this.BasicListBoxAssociate1.ListBox = this.HexListBox1;
            this.BasicListBoxAssociate1.Location = new System.Drawing.Point(273, 17);
            this.BasicListBoxAssociate1.Margin = new System.Windows.Forms.Padding(4);
            this.BasicListBoxAssociate1.Name = "BasicListBoxAssociate1";
            this.BasicListBoxAssociate1.Padding = new System.Windows.Forms.Padding(4);
            this.BasicListBoxAssociate1.Size = new System.Drawing.Size(485, 550);
            this.BasicListBoxAssociate1.TabIndex = 15;
            this.BasicListBoxAssociate1.TabStop = false;
            this.BasicListBoxAssociate1.Text = "HexListBox1";
            // 
            // HexPanel1
            // 
            this.HexPanel1.Controls.Add(this.Battler5);
            this.HexPanel1.Controls.Add(this.Battler4);
            this.HexPanel1.Controls.Add(this.Battler3);
            this.HexPanel1.Controls.Add(this.Battler2);
            this.HexPanel1.Controls.Add(this.Battler1);
            this.HexPanel1.Controls.Add(this.Label5);
            this.HexPanel1.Controls.Add(this.Label1);
            this.HexPanel1.Controls.Add(this.Label4);
            this.HexPanel1.Controls.Add(this.Label2);
            this.HexPanel1.Controls.Add(this.Label3);
            this.HexPanel1.IndexOffset = "&H000005";
            this.HexPanel1.Location = new System.Drawing.Point(8, 28);
            this.HexPanel1.Margin = new System.Windows.Forms.Padding(4);
            this.HexPanel1.Name = "HexPanel1";
            this.HexPanel1.Size = new System.Drawing.Size(470, 180);
            this.HexPanel1.TabIndex = 25;
            // 
            // Battler5
            // 
            this.Battler5.Display = HexTools.HexEnumerations.DisplayType.Hex;
            this.Battler5.DisplayMember = "Text";
            this.Battler5.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.Battler5.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.Battler5.Endian = HexTools.HexEnumerations.EndianType.Little_Endian;
            this.Battler5.FormatString = "X2";
            this.Battler5.FormattingEnabled = true;
            this.Battler5.HexOffset = "&H013F0F";
            this.Battler5.ItemCollection = "Data_Battlers.HexListBox1";
            this.Battler5.Location = new System.Drawing.Point(80, 145);
            this.Battler5.Margin = new System.Windows.Forms.Padding(4);
            this.Battler5.MaxDropDownItems = 15;
            this.Battler5.MaxLength = 1;
            this.Battler5.Name = "Battler5";
            this.Battler5.NullValue = "&HFF";
            this.Battler5.Size = new System.Drawing.Size(256, 23);
            this.Battler5.TabIndex = 36;
            this.Battler5.ValueDisplay = true;
            this.Battler5.ValueMember = "Value";
            // 
            // Battler4
            // 
            this.Battler4.Display = HexTools.HexEnumerations.DisplayType.Hex;
            this.Battler4.DisplayMember = "Text";
            this.Battler4.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.Battler4.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.Battler4.Endian = HexTools.HexEnumerations.EndianType.Little_Endian;
            this.Battler4.FormatString = "X2";
            this.Battler4.FormattingEnabled = true;
            this.Battler4.HexOffset = "&H013F0E";
            this.Battler4.ItemCollection = "Data_Battlers.HexListBox1";
            this.Battler4.Location = new System.Drawing.Point(80, 112);
            this.Battler4.Margin = new System.Windows.Forms.Padding(4);
            this.Battler4.MaxDropDownItems = 15;
            this.Battler4.MaxLength = 1;
            this.Battler4.Name = "Battler4";
            this.Battler4.NullValue = "&HFF";
            this.Battler4.Size = new System.Drawing.Size(256, 23);
            this.Battler4.TabIndex = 35;
            this.Battler4.ValueDisplay = true;
            this.Battler4.ValueMember = "Value";
            // 
            // Battler3
            // 
            this.Battler3.Display = HexTools.HexEnumerations.DisplayType.Hex;
            this.Battler3.DisplayMember = "Text";
            this.Battler3.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.Battler3.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.Battler3.Endian = HexTools.HexEnumerations.EndianType.Little_Endian;
            this.Battler3.FormatString = "X2";
            this.Battler3.FormattingEnabled = true;
            this.Battler3.HexOffset = "&H013F0B";
            this.Battler3.ItemCollection = "Data_Battlers.HexListBox1";
            this.Battler3.Location = new System.Drawing.Point(80, 79);
            this.Battler3.Margin = new System.Windows.Forms.Padding(4);
            this.Battler3.MaxDropDownItems = 15;
            this.Battler3.MaxLength = 1;
            this.Battler3.Name = "Battler3";
            this.Battler3.NullValue = "&HFF";
            this.Battler3.Size = new System.Drawing.Size(256, 23);
            this.Battler3.TabIndex = 34;
            this.Battler3.ValueDisplay = true;
            this.Battler3.ValueMember = "Value";
            // 
            // Battler2
            // 
            this.Battler2.Display = HexTools.HexEnumerations.DisplayType.Hex;
            this.Battler2.DisplayMember = "Text";
            this.Battler2.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.Battler2.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.Battler2.Endian = HexTools.HexEnumerations.EndianType.Little_Endian;
            this.Battler2.FormatString = "X2";
            this.Battler2.FormattingEnabled = true;
            this.Battler2.HexOffset = "&H013F0D";
            this.Battler2.ItemCollection = "Data_Battlers.HexListBox1";
            this.Battler2.Location = new System.Drawing.Point(80, 46);
            this.Battler2.Margin = new System.Windows.Forms.Padding(4);
            this.Battler2.MaxDropDownItems = 15;
            this.Battler2.MaxLength = 1;
            this.Battler2.Name = "Battler2";
            this.Battler2.NullValue = "&HFF";
            this.Battler2.Size = new System.Drawing.Size(256, 23);
            this.Battler2.TabIndex = 33;
            this.Battler2.ValueDisplay = true;
            this.Battler2.ValueMember = "Value";
            // 
            // Battler1
            // 
            this.Battler1.Display = HexTools.HexEnumerations.DisplayType.Hex;
            this.Battler1.DisplayMember = "Text";
            this.Battler1.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.Battler1.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.Battler1.Endian = HexTools.HexEnumerations.EndianType.Little_Endian;
            this.Battler1.FormatString = "X2";
            this.Battler1.FormattingEnabled = true;
            this.Battler1.HexOffset = "&H013F0C";
            this.Battler1.ItemCollection = "Data_Battlers.HexListBox1";
            this.Battler1.Location = new System.Drawing.Point(80, 12);
            this.Battler1.Margin = new System.Windows.Forms.Padding(4);
            this.Battler1.MaxDropDownItems = 15;
            this.Battler1.MaxLength = 1;
            this.Battler1.Name = "Battler1";
            this.Battler1.NullValue = "&HFF";
            this.Battler1.Size = new System.Drawing.Size(256, 23);
            this.Battler1.TabIndex = 32;
            this.Battler1.ValueDisplay = true;
            this.Battler1.ValueMember = "Value";
            // 
            // Label5
            // 
            this.Label5.AutoSize = true;
            this.Label5.Location = new System.Drawing.Point(8, 149);
            this.Label5.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.Label5.Name = "Label5";
            this.Label5.Size = new System.Drawing.Size(69, 17);
            this.Label5.TabIndex = 23;
            this.Label5.Text = "Battler #5";
            // 
            // Label1
            // 
            this.Label1.AutoSize = true;
            this.Label1.Location = new System.Drawing.Point(8, 16);
            this.Label1.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.Label1.Name = "Label1";
            this.Label1.Size = new System.Drawing.Size(69, 17);
            this.Label1.TabIndex = 15;
            this.Label1.Text = "Battler #1";
            // 
            // Label4
            // 
            this.Label4.AutoSize = true;
            this.Label4.Location = new System.Drawing.Point(8, 116);
            this.Label4.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.Label4.Name = "Label4";
            this.Label4.Size = new System.Drawing.Size(69, 17);
            this.Label4.TabIndex = 21;
            this.Label4.Text = "Battler #4";
            // 
            // Label2
            // 
            this.Label2.AutoSize = true;
            this.Label2.Location = new System.Drawing.Point(8, 49);
            this.Label2.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.Label2.Name = "Label2";
            this.Label2.Size = new System.Drawing.Size(69, 17);
            this.Label2.TabIndex = 17;
            this.Label2.Text = "Battler #2";
            // 
            // Label3
            // 
            this.Label3.AutoSize = true;
            this.Label3.Location = new System.Drawing.Point(8, 82);
            this.Label3.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.Label3.Name = "Label3";
            this.Label3.Size = new System.Drawing.Size(69, 17);
            this.Label3.TabIndex = 19;
            this.Label3.Text = "Battler #3";
            // 
            // Data_Groups
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.BasicListBoxAssociate1);
            this.Controls.Add(this.HexListBox1);
            this.Margin = new System.Windows.Forms.Padding(4);
            this.Name = "Data_Groups";
            this.Size = new System.Drawing.Size(787, 603);
            this.BasicListBoxAssociate1.ResumeLayout(false);
            this.HexPanel1.ResumeLayout(false);
            this.HexPanel1.PerformLayout();
            this.ResumeLayout(false);

        }
        internal HexTools.HexListBox HexListBox1;
        internal BasicTools.BasicControls.BasicListBoxAssociate BasicListBoxAssociate1;
        internal HexTools.HexPanel HexPanel1;
        internal HexTools.HexComboBox Battler5;
        internal HexTools.HexComboBox Battler4;
        internal HexTools.HexComboBox Battler3;
        internal HexTools.HexComboBox Battler2;
        internal HexTools.HexComboBox Battler1;
        internal Label Label5;
        internal Label Label1;
        internal Label Label4;
        internal Label Label2;
        internal Label Label3;
    }
}