using System.Diagnostics;
using System.Drawing;
using System.Windows.Forms;

namespace DBZ_LotSS_Editor
{
    [Microsoft.VisualBasic.CompilerServices.DesignerGenerated()]
    public partial class Text_Game : HexTools.HexUserControl
    {

        // Form overrides dispose to clean up the component list.
        [DebuggerNonUserCode()]
        protected override void Dispose(bool disposing)
        {
            try
            {
                if (disposing && components != null)
                {
                    components.Dispose();
                }
            }
            finally
            {
                base.Dispose(disposing);
            }
        }

        // Required by the Windows Form Designer
        private System.ComponentModel.IContainer components;

        // NOTE: The following procedure is required by the Windows Form Designer
        // It can be modified using the Windows Form Designer.  
        // Do not modify it using the code editor.
        [DebuggerStepThrough()]
        private void InitializeComponent()
        {
            HexTools.HexListBoxItem hexListBoxItem1 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem2 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem3 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem4 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem5 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem6 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem7 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem8 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem9 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem10 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem11 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem12 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem13 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem14 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem15 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem16 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem17 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem18 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem19 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem20 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem21 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem22 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem23 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem24 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem25 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem26 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem27 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem28 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem29 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem30 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem31 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem32 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem33 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem34 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem35 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem36 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem37 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem38 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem39 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem40 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem41 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem42 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem43 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem44 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem45 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem46 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem47 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem48 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem49 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem50 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem51 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem52 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem53 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem54 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem55 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem56 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem57 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem58 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem59 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem60 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem61 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem62 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem63 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem64 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem65 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem66 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem67 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem68 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem69 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem70 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem71 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem72 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem73 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem74 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem75 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem76 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem77 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem78 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem79 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem80 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem81 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem82 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem83 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem84 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem85 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem86 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem87 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem88 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem89 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem90 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem91 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem92 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem93 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem94 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem95 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem96 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem97 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem98 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem99 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem100 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem101 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem102 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem103 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem104 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem105 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem106 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem107 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem108 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem109 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem110 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem111 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem112 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem113 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem114 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem115 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem116 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem117 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem118 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem119 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem120 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem121 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem122 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem123 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem124 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem125 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem126 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem127 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem128 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem129 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem130 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem131 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem132 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem133 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem134 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem135 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem136 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem137 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem138 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem139 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem140 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem141 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem142 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem143 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem144 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem145 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem146 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem147 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem148 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem149 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem150 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem151 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem152 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem153 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem154 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem155 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem156 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem157 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem158 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem159 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem160 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem161 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem162 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem163 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem164 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem165 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem166 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem167 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem168 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem169 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem170 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem171 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem172 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem173 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem174 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem175 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem176 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem177 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem178 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem179 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem180 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem181 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem182 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem183 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem184 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem185 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem186 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem187 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem188 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem189 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem190 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem191 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem192 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem193 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem194 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem195 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem196 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem197 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem198 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem199 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem200 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem201 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem202 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem203 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem204 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem205 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem206 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem207 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem208 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem209 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem210 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem211 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem212 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem213 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem214 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem215 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem216 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem217 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem218 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem219 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem220 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem221 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem222 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem223 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem224 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem225 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem226 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem227 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem228 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem229 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem230 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem231 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem232 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem233 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem234 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem235 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem236 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem237 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem238 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem239 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem240 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem241 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem242 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem243 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem244 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem245 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem246 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem247 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem248 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem249 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem250 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem251 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem252 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem253 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem254 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem255 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem256 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem257 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem258 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem259 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem260 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem261 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem262 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem263 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem264 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem265 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem266 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem267 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem268 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem269 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem270 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem271 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem272 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem273 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem274 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem275 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem276 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem277 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem278 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem279 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem280 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem281 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem282 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem283 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem284 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem285 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem286 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem287 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem288 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem289 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem290 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem291 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem292 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem293 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem294 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem295 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem296 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem297 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem298 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem299 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem300 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem301 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem302 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem303 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem304 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem305 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem306 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem307 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem308 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem309 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem310 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem311 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem312 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem313 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem314 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem315 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem316 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem317 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem318 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem319 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem320 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem321 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem322 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem323 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem324 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem325 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem326 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem327 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem328 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem329 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem330 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem331 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem332 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem333 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem334 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem335 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem336 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem337 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem338 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem339 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem340 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem341 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem342 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem343 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem344 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem345 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem346 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem347 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem348 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem349 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem350 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem351 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem352 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem353 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem354 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem355 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem356 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem357 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem358 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem359 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem360 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem361 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem362 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem363 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem364 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem365 = new HexTools.HexListBoxItem();
            HexTools.HexListBoxItem hexListBoxItem366 = new HexTools.HexListBoxItem();
            this.BasicListBoxAssociate1 = new BasicTools.BasicControls.BasicListBoxAssociate();
            this.MessageBox = new HexTools.HexMessageBox();
            this.HexListBox1 = new HexTools.HexListBox();
            this.BasicListBoxAssociate1.SuspendLayout();
            this.SuspendLayout();
            // 
            // BasicListBoxAssociate1
            // 
            this.BasicListBoxAssociate1.Controls.Add(this.MessageBox);
            this.BasicListBoxAssociate1.ListBox = this.HexListBox1;
            this.BasicListBoxAssociate1.Location = new System.Drawing.Point(255, 17);
            this.BasicListBoxAssociate1.Name = "BasicListBoxAssociate1";
            this.BasicListBoxAssociate1.Size = new System.Drawing.Size(518, 550);
            this.BasicListBoxAssociate1.TabIndex = 19;
            this.BasicListBoxAssociate1.TabStop = false;
            this.BasicListBoxAssociate1.Text = "HexListBox1";
            // 
            // MessageBox
            // 
            this.MessageBox.AutoSize = true;
            this.MessageBox.Location = new System.Drawing.Point(6, 21);
            this.MessageBox.MinimumSize = new System.Drawing.Size(250, 125);
            this.MessageBox.Name = "MessageBox";
            this.MessageBox.Size = new System.Drawing.Size(316, 267);
            this.MessageBox.TabIndex = 0;
            // 
            // HexListBox1
            // 
            this.HexListBox1.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.HexListBox1.FormatString = "X2";
            this.HexListBox1.FormattingEnabled = true;
            this.HexListBox1.IndexDisplay = true;
            hexListBoxItem1.Text = "Index00";
            hexListBoxItem2.Text = "Index01";
            hexListBoxItem3.Text = "Index02";
            hexListBoxItem4.Text = "Index03";
            hexListBoxItem5.Text = "Index04";
            hexListBoxItem6.Text = "Index05";
            hexListBoxItem7.Text = "Index06";
            hexListBoxItem8.Text = "Index07";
            hexListBoxItem9.Text = "Index08";
            hexListBoxItem10.Text = "Index09";
            hexListBoxItem11.Text = "Index10";
            hexListBoxItem12.Text = "Index11";
            hexListBoxItem13.Text = "Index12";
            hexListBoxItem14.Text = "Index13";
            hexListBoxItem15.Text = "Index14";
            hexListBoxItem16.Text = "Index15";
            hexListBoxItem17.Text = "Index16";
            hexListBoxItem18.Text = "Index17";
            hexListBoxItem19.Text = "Index18";
            hexListBoxItem20.Text = "Index19";
            hexListBoxItem21.Text = "Index20";
            hexListBoxItem22.Text = "Index21";
            hexListBoxItem23.Text = "Index22";
            hexListBoxItem24.Text = "Index23";
            hexListBoxItem25.Text = "Index24";
            hexListBoxItem26.Text = "Index25";
            hexListBoxItem27.Text = "Index26";
            hexListBoxItem28.Text = "Index27";
            hexListBoxItem29.Text = "Index28";
            hexListBoxItem30.Text = "Index29";
            hexListBoxItem31.Text = "Index30";
            hexListBoxItem32.Text = "Index31";
            hexListBoxItem33.Text = "Index32";
            hexListBoxItem34.Text = "Index33";
            hexListBoxItem35.Text = "Index34";
            hexListBoxItem36.Text = "Index35";
            hexListBoxItem37.Text = "Index36";
            hexListBoxItem38.Text = "Index37";
            hexListBoxItem39.Text = "Index38";
            hexListBoxItem40.Text = "Index39";
            hexListBoxItem41.Text = "Index40";
            hexListBoxItem42.Text = "Index41";
            hexListBoxItem43.Text = "Index42";
            hexListBoxItem44.Text = "Index43";
            hexListBoxItem45.Text = "Index44";
            hexListBoxItem46.Text = "Index45";
            hexListBoxItem47.Text = "Index46";
            hexListBoxItem48.Text = "Index47";
            hexListBoxItem49.Text = "Index48";
            hexListBoxItem50.Text = "Index49";
            hexListBoxItem51.Text = "Index50";
            hexListBoxItem52.Text = "Index51";
            hexListBoxItem53.Text = "Index52";
            hexListBoxItem54.Text = "Index53";
            hexListBoxItem55.Text = "Index54";
            hexListBoxItem56.Text = "Index55";
            hexListBoxItem57.Text = "Index56";
            hexListBoxItem58.Text = "Index57";
            hexListBoxItem59.Text = "Index58";
            hexListBoxItem60.Text = "Index59";
            hexListBoxItem61.Text = "Index60";
            hexListBoxItem62.Text = "Index61";
            hexListBoxItem63.Text = "Index62";
            hexListBoxItem64.Text = "Index63";
            hexListBoxItem65.Text = "Index64";
            hexListBoxItem66.Text = "Index65";
            hexListBoxItem67.Text = "Index66";
            hexListBoxItem68.Text = "Index67";
            hexListBoxItem69.Text = "Index68";
            hexListBoxItem70.Text = "Index69";
            hexListBoxItem71.Text = "Index70";
            hexListBoxItem72.Text = "Index71";
            hexListBoxItem73.Text = "Index72";
            hexListBoxItem74.Text = "Index73";
            hexListBoxItem75.Text = "Index74";
            hexListBoxItem76.Text = "Index75";
            hexListBoxItem77.Text = "Index76";
            hexListBoxItem78.Text = "Index77";
            hexListBoxItem79.Text = "Index78";
            hexListBoxItem80.Text = "Index79";
            hexListBoxItem81.Text = "Index80";
            hexListBoxItem82.Text = "Index81";
            hexListBoxItem83.Text = "Index82";
            hexListBoxItem84.Text = "Index83";
            hexListBoxItem85.Text = "Index84";
            hexListBoxItem86.Text = "Index85";
            hexListBoxItem87.Text = "Index86";
            hexListBoxItem88.Text = "Index87";
            hexListBoxItem89.Text = "Index88";
            hexListBoxItem90.Text = "Index89";
            hexListBoxItem91.Text = "Index90";
            hexListBoxItem92.Text = "Index91";
            hexListBoxItem93.Text = "Index92";
            hexListBoxItem94.Text = "Index93";
            hexListBoxItem95.Text = "Index94";
            hexListBoxItem96.Text = "Index95";
            hexListBoxItem97.Text = "Index96";
            hexListBoxItem98.Text = "Index97";
            hexListBoxItem99.Text = "Index98";
            hexListBoxItem100.Text = "Index99";
            hexListBoxItem101.Text = "Index100";
            hexListBoxItem102.Text = "Index101";
            hexListBoxItem103.Text = "Index102";
            hexListBoxItem104.Text = "Index103";
            hexListBoxItem105.Text = "Index104";
            hexListBoxItem106.Text = "Index105";
            hexListBoxItem107.Text = "Index106";
            hexListBoxItem108.Text = "Index107";
            hexListBoxItem109.Text = "Index108";
            hexListBoxItem110.Text = "Index109";
            hexListBoxItem111.Text = "Index110";
            hexListBoxItem112.Text = "Index111";
            hexListBoxItem113.Text = "Index112";
            hexListBoxItem114.Text = "Index113";
            hexListBoxItem115.Text = "Index114";
            hexListBoxItem116.Text = "Index115";
            hexListBoxItem117.Text = "Index116";
            hexListBoxItem118.Text = "Index117";
            hexListBoxItem119.Text = "Index118";
            hexListBoxItem120.Text = "Index119";
            hexListBoxItem121.Text = "Index120";
            hexListBoxItem122.Text = "Index121";
            hexListBoxItem123.Text = "Index122";
            hexListBoxItem124.Text = "Index123";
            hexListBoxItem125.Text = "Index124";
            hexListBoxItem126.Text = "Index125";
            hexListBoxItem127.Text = "Index126";
            hexListBoxItem128.Text = "Index127";
            hexListBoxItem129.Text = "Index128";
            hexListBoxItem130.Text = "Index129";
            hexListBoxItem131.Text = "Index130";
            hexListBoxItem132.Text = "Index131";
            hexListBoxItem133.Text = "Index132";
            hexListBoxItem134.Text = "Index133";
            hexListBoxItem135.Text = "Index134";
            hexListBoxItem136.Text = "Index135";
            hexListBoxItem137.Text = "Index136";
            hexListBoxItem138.Text = "Index137";
            hexListBoxItem139.Text = "Index138";
            hexListBoxItem140.Text = "Index139";
            hexListBoxItem141.Text = "Index140";
            hexListBoxItem142.Text = "Index141";
            hexListBoxItem143.Text = "Index142";
            hexListBoxItem144.Text = "Index143";
            hexListBoxItem145.Text = "Index144";
            hexListBoxItem146.Text = "Index145";
            hexListBoxItem147.Text = "Index146";
            hexListBoxItem148.Text = "Index147";
            hexListBoxItem149.Text = "Index148";
            hexListBoxItem150.Text = "Index149";
            hexListBoxItem151.Text = "Index150";
            hexListBoxItem152.Text = "Index151";
            hexListBoxItem153.Text = "Index152";
            hexListBoxItem154.Text = "Index153";
            hexListBoxItem155.Text = "Index154";
            hexListBoxItem156.Text = "Index155";
            hexListBoxItem157.Text = "Index146";
            hexListBoxItem158.Text = "Index157";
            hexListBoxItem159.Text = "Index158";
            hexListBoxItem160.Text = "Index159";
            hexListBoxItem161.Text = "Index160";
            hexListBoxItem162.Text = "Index161";
            hexListBoxItem163.Text = "Index162";
            hexListBoxItem164.Text = "Index163";
            hexListBoxItem165.Text = "Index164";
            hexListBoxItem166.Text = "Index165";
            hexListBoxItem167.Text = "Index166";
            hexListBoxItem168.Text = "Index167";
            hexListBoxItem169.Text = "Index168";
            hexListBoxItem170.Text = "Index169";
            hexListBoxItem171.Text = "Index170";
            hexListBoxItem172.Text = "Index171";
            hexListBoxItem173.Text = "Index172";
            hexListBoxItem174.Text = "Index173";
            hexListBoxItem175.Text = "Index174";
            hexListBoxItem176.Text = "Index175";
            hexListBoxItem177.Text = "Index176";
            hexListBoxItem178.Text = "Index177";
            hexListBoxItem179.Text = "Index178";
            hexListBoxItem180.Text = "Index179";
            hexListBoxItem181.Text = "Index180";
            hexListBoxItem182.Text = "Index181";
            hexListBoxItem183.Text = "Index182";
            hexListBoxItem184.Text = "Index183";
            hexListBoxItem185.Text = "Index184";
            hexListBoxItem186.Text = "Index185";
            hexListBoxItem187.Text = "Index186";
            hexListBoxItem188.Text = "Index187";
            hexListBoxItem189.Text = "Index188";
            hexListBoxItem190.Text = "Index189";
            hexListBoxItem191.Text = "Index190";
            hexListBoxItem192.Text = "Index191";
            hexListBoxItem193.Text = "Index192";
            hexListBoxItem194.Text = "Index193";
            hexListBoxItem195.Text = "Index194";
            hexListBoxItem196.Text = "Index195";
            hexListBoxItem197.Text = "Index196";
            hexListBoxItem198.Text = "Index197";
            hexListBoxItem199.Text = "Index198";
            hexListBoxItem200.Text = "Index199";
            hexListBoxItem201.Text = "Index200";
            hexListBoxItem202.Text = "Index201";
            hexListBoxItem203.Text = "Index202";
            hexListBoxItem204.Text = "Index203";
            hexListBoxItem205.Text = "Index204";
            hexListBoxItem206.Text = "Index205";
            hexListBoxItem207.Text = "Index206";
            hexListBoxItem208.Text = "Index207";
            hexListBoxItem209.Text = "Index208";
            hexListBoxItem210.Text = "Index209";
            hexListBoxItem211.Text = "Index210";
            hexListBoxItem212.Text = "Index211";
            hexListBoxItem213.Text = "Index212";
            hexListBoxItem214.Text = "Index213";
            hexListBoxItem215.Text = "Index214";
            hexListBoxItem216.Text = "Index215";
            hexListBoxItem217.Text = "Index216";
            hexListBoxItem218.Text = "Index217";
            hexListBoxItem219.Text = "Index218";
            hexListBoxItem220.Text = "Index219";
            hexListBoxItem221.Text = "Index220";
            hexListBoxItem222.Text = "Index221";
            hexListBoxItem223.Text = "Index222";
            hexListBoxItem224.Text = "Index223";
            hexListBoxItem225.Text = "Index224";
            hexListBoxItem226.Text = "Index225";
            hexListBoxItem227.Text = "Index226";
            hexListBoxItem228.Text = "Index227";
            hexListBoxItem229.Text = "Index228";
            hexListBoxItem230.Text = "Index229";
            hexListBoxItem231.Text = "Index230";
            hexListBoxItem232.Text = "Index231";
            hexListBoxItem233.Text = "Index232";
            hexListBoxItem234.Text = "Index233";
            hexListBoxItem235.Text = "Index234";
            hexListBoxItem236.Text = "Index235";
            hexListBoxItem237.Text = "Index236";
            hexListBoxItem238.Text = "Index237";
            hexListBoxItem239.Text = "Index238";
            hexListBoxItem240.Text = "Index239";
            hexListBoxItem241.Text = "Index240";
            hexListBoxItem242.Text = "Index241";
            hexListBoxItem243.Text = "Index242";
            hexListBoxItem244.Text = "Index243";
            hexListBoxItem245.Text = "Index244";
            hexListBoxItem246.Text = "Index245";
            hexListBoxItem247.Text = "Index246";
            hexListBoxItem248.Text = "Index247";
            hexListBoxItem249.Text = "Index248";
            hexListBoxItem250.Text = "Index249";
            hexListBoxItem251.Text = "Index250";
            hexListBoxItem252.Text = "Index251";
            hexListBoxItem253.Text = "Index252";
            hexListBoxItem254.Text = "Index253";
            hexListBoxItem255.Text = "Index254";
            hexListBoxItem256.Text = "Index255";
            hexListBoxItem257.Text = "Index256";
            hexListBoxItem258.Text = "Index257";
            hexListBoxItem259.Text = "Index258";
            hexListBoxItem260.Text = "Index259";
            hexListBoxItem261.Text = "Index260";
            hexListBoxItem262.Text = "Index261";
            hexListBoxItem263.Text = "Index262";
            hexListBoxItem264.Text = "Index263";
            hexListBoxItem265.Text = "Index264";
            hexListBoxItem266.Text = "Index265";
            hexListBoxItem267.Text = "Index266";
            hexListBoxItem268.Text = "Index267";
            hexListBoxItem269.Text = "Index268";
            hexListBoxItem270.Text = "Index269";
            hexListBoxItem271.Text = "Index270";
            hexListBoxItem272.Text = "Index271";
            hexListBoxItem273.Text = "Index272";
            hexListBoxItem274.Text = "Index273";
            hexListBoxItem275.Text = "Index274";
            hexListBoxItem276.Text = "Index275";
            hexListBoxItem277.Text = "Index276";
            hexListBoxItem278.Text = "Index277";
            hexListBoxItem279.Text = "Index278";
            hexListBoxItem280.Text = "Index279";
            hexListBoxItem281.Text = "Index280";
            hexListBoxItem282.Text = "Index281";
            hexListBoxItem283.Text = "Index282";
            hexListBoxItem284.Text = "Index283";
            hexListBoxItem285.Text = "Index284";
            hexListBoxItem286.Text = "Index285";
            hexListBoxItem287.Text = "Index286";
            hexListBoxItem288.Text = "Index287";
            hexListBoxItem289.Text = "Index288";
            hexListBoxItem290.Text = "Index289";
            hexListBoxItem291.Text = "Index290";
            hexListBoxItem292.Text = "Index291";
            hexListBoxItem293.Text = "Index292";
            hexListBoxItem294.Text = "Index293";
            hexListBoxItem295.Text = "Index294";
            hexListBoxItem296.Text = "Index295";
            hexListBoxItem297.Text = "Index296";
            hexListBoxItem298.Text = "Index297";
            hexListBoxItem299.Text = "Index298";
            hexListBoxItem300.Text = "Index299";
            hexListBoxItem301.Text = "Index300";
            hexListBoxItem302.Text = "Index301";
            hexListBoxItem303.Text = "Index302";
            hexListBoxItem304.Text = "Index303";
            hexListBoxItem305.Text = "Index304";
            hexListBoxItem306.Text = "Index305";
            hexListBoxItem307.Text = "Index306";
            hexListBoxItem308.Text = "Index307";
            hexListBoxItem309.Text = "Index308";
            hexListBoxItem310.Text = "Index309";
            hexListBoxItem311.Text = "Index310";
            hexListBoxItem312.Text = "Index311";
            hexListBoxItem313.Text = "Index312";
            hexListBoxItem314.Text = "Index313";
            hexListBoxItem315.Text = "Index314";
            hexListBoxItem316.Text = "Index315";
            hexListBoxItem317.Text = "Index316";
            hexListBoxItem318.Text = "Index317";
            hexListBoxItem319.Text = "Index318";
            hexListBoxItem320.Text = "Index319";
            hexListBoxItem321.Text = "Index320";
            hexListBoxItem322.Text = "Index321";
            hexListBoxItem323.Text = "Index322";
            hexListBoxItem324.Text = "Index323";
            hexListBoxItem325.Text = "Index324";
            hexListBoxItem326.Text = "Index325";
            hexListBoxItem327.Text = "Index326";
            hexListBoxItem328.Text = "Index327";
            hexListBoxItem329.Text = "Index328";
            hexListBoxItem330.Text = "Index329";
            hexListBoxItem331.Text = "Index330";
            hexListBoxItem332.Text = "Index331";
            hexListBoxItem333.Text = "Index332";
            hexListBoxItem334.Text = "Index333";
            hexListBoxItem335.Text = "Index334";
            hexListBoxItem336.Text = "Index335";
            hexListBoxItem337.Text = "Index336";
            hexListBoxItem338.Text = "Index337";
            hexListBoxItem339.Text = "Index338";
            hexListBoxItem340.Text = "Index339";
            hexListBoxItem341.Text = "Index340";
            hexListBoxItem342.Text = "Index341";
            hexListBoxItem343.Text = "Index342";
            hexListBoxItem344.Text = "Index343";
            hexListBoxItem345.Text = "Index344";
            hexListBoxItem346.Text = "Index345";
            hexListBoxItem347.Text = "Index346";
            hexListBoxItem348.Text = "Index347";
            hexListBoxItem349.Text = "Index348";
            hexListBoxItem350.Text = "Index349";
            hexListBoxItem351.Text = "Index350";
            hexListBoxItem352.Text = "Index351";
            hexListBoxItem353.Text = "Index352";
            hexListBoxItem354.Text = "Index353";
            hexListBoxItem355.Text = "Index354";
            hexListBoxItem356.Text = "Index355";
            hexListBoxItem357.Text = "Index356";
            hexListBoxItem358.Text = "Index357";
            hexListBoxItem359.Text = "Index358";
            hexListBoxItem360.Text = "Index359";
            hexListBoxItem361.Text = "Index360";
            hexListBoxItem362.Text = "Index361";
            hexListBoxItem363.Text = "Index362";
            hexListBoxItem364.Text = "Index363";
            hexListBoxItem365.Text = "Index364";
            hexListBoxItem366.Text = "Index365";
            this.HexListBox1.Items.Add(hexListBoxItem1);
            this.HexListBox1.Items.Add(hexListBoxItem2);
            this.HexListBox1.Items.Add(hexListBoxItem3);
            this.HexListBox1.Items.Add(hexListBoxItem4);
            this.HexListBox1.Items.Add(hexListBoxItem5);
            this.HexListBox1.Items.Add(hexListBoxItem6);
            this.HexListBox1.Items.Add(hexListBoxItem7);
            this.HexListBox1.Items.Add(hexListBoxItem8);
            this.HexListBox1.Items.Add(hexListBoxItem9);
            this.HexListBox1.Items.Add(hexListBoxItem10);
            this.HexListBox1.Items.Add(hexListBoxItem11);
            this.HexListBox1.Items.Add(hexListBoxItem12);
            this.HexListBox1.Items.Add(hexListBoxItem13);
            this.HexListBox1.Items.Add(hexListBoxItem14);
            this.HexListBox1.Items.Add(hexListBoxItem15);
            this.HexListBox1.Items.Add(hexListBoxItem16);
            this.HexListBox1.Items.Add(hexListBoxItem17);
            this.HexListBox1.Items.Add(hexListBoxItem18);
            this.HexListBox1.Items.Add(hexListBoxItem19);
            this.HexListBox1.Items.Add(hexListBoxItem20);
            this.HexListBox1.Items.Add(hexListBoxItem21);
            this.HexListBox1.Items.Add(hexListBoxItem22);
            this.HexListBox1.Items.Add(hexListBoxItem23);
            this.HexListBox1.Items.Add(hexListBoxItem24);
            this.HexListBox1.Items.Add(hexListBoxItem25);
            this.HexListBox1.Items.Add(hexListBoxItem26);
            this.HexListBox1.Items.Add(hexListBoxItem27);
            this.HexListBox1.Items.Add(hexListBoxItem28);
            this.HexListBox1.Items.Add(hexListBoxItem29);
            this.HexListBox1.Items.Add(hexListBoxItem30);
            this.HexListBox1.Items.Add(hexListBoxItem31);
            this.HexListBox1.Items.Add(hexListBoxItem32);
            this.HexListBox1.Items.Add(hexListBoxItem33);
            this.HexListBox1.Items.Add(hexListBoxItem34);
            this.HexListBox1.Items.Add(hexListBoxItem35);
            this.HexListBox1.Items.Add(hexListBoxItem36);
            this.HexListBox1.Items.Add(hexListBoxItem37);
            this.HexListBox1.Items.Add(hexListBoxItem38);
            this.HexListBox1.Items.Add(hexListBoxItem39);
            this.HexListBox1.Items.Add(hexListBoxItem40);
            this.HexListBox1.Items.Add(hexListBoxItem41);
            this.HexListBox1.Items.Add(hexListBoxItem42);
            this.HexListBox1.Items.Add(hexListBoxItem43);
            this.HexListBox1.Items.Add(hexListBoxItem44);
            this.HexListBox1.Items.Add(hexListBoxItem45);
            this.HexListBox1.Items.Add(hexListBoxItem46);
            this.HexListBox1.Items.Add(hexListBoxItem47);
            this.HexListBox1.Items.Add(hexListBoxItem48);
            this.HexListBox1.Items.Add(hexListBoxItem49);
            this.HexListBox1.Items.Add(hexListBoxItem50);
            this.HexListBox1.Items.Add(hexListBoxItem51);
            this.HexListBox1.Items.Add(hexListBoxItem52);
            this.HexListBox1.Items.Add(hexListBoxItem53);
            this.HexListBox1.Items.Add(hexListBoxItem54);
            this.HexListBox1.Items.Add(hexListBoxItem55);
            this.HexListBox1.Items.Add(hexListBoxItem56);
            this.HexListBox1.Items.Add(hexListBoxItem57);
            this.HexListBox1.Items.Add(hexListBoxItem58);
            this.HexListBox1.Items.Add(hexListBoxItem59);
            this.HexListBox1.Items.Add(hexListBoxItem60);
            this.HexListBox1.Items.Add(hexListBoxItem61);
            this.HexListBox1.Items.Add(hexListBoxItem62);
            this.HexListBox1.Items.Add(hexListBoxItem63);
            this.HexListBox1.Items.Add(hexListBoxItem64);
            this.HexListBox1.Items.Add(hexListBoxItem65);
            this.HexListBox1.Items.Add(hexListBoxItem66);
            this.HexListBox1.Items.Add(hexListBoxItem67);
            this.HexListBox1.Items.Add(hexListBoxItem68);
            this.HexListBox1.Items.Add(hexListBoxItem69);
            this.HexListBox1.Items.Add(hexListBoxItem70);
            this.HexListBox1.Items.Add(hexListBoxItem71);
            this.HexListBox1.Items.Add(hexListBoxItem72);
            this.HexListBox1.Items.Add(hexListBoxItem73);
            this.HexListBox1.Items.Add(hexListBoxItem74);
            this.HexListBox1.Items.Add(hexListBoxItem75);
            this.HexListBox1.Items.Add(hexListBoxItem76);
            this.HexListBox1.Items.Add(hexListBoxItem77);
            this.HexListBox1.Items.Add(hexListBoxItem78);
            this.HexListBox1.Items.Add(hexListBoxItem79);
            this.HexListBox1.Items.Add(hexListBoxItem80);
            this.HexListBox1.Items.Add(hexListBoxItem81);
            this.HexListBox1.Items.Add(hexListBoxItem82);
            this.HexListBox1.Items.Add(hexListBoxItem83);
            this.HexListBox1.Items.Add(hexListBoxItem84);
            this.HexListBox1.Items.Add(hexListBoxItem85);
            this.HexListBox1.Items.Add(hexListBoxItem86);
            this.HexListBox1.Items.Add(hexListBoxItem87);
            this.HexListBox1.Items.Add(hexListBoxItem88);
            this.HexListBox1.Items.Add(hexListBoxItem89);
            this.HexListBox1.Items.Add(hexListBoxItem90);
            this.HexListBox1.Items.Add(hexListBoxItem91);
            this.HexListBox1.Items.Add(hexListBoxItem92);
            this.HexListBox1.Items.Add(hexListBoxItem93);
            this.HexListBox1.Items.Add(hexListBoxItem94);
            this.HexListBox1.Items.Add(hexListBoxItem95);
            this.HexListBox1.Items.Add(hexListBoxItem96);
            this.HexListBox1.Items.Add(hexListBoxItem97);
            this.HexListBox1.Items.Add(hexListBoxItem98);
            this.HexListBox1.Items.Add(hexListBoxItem99);
            this.HexListBox1.Items.Add(hexListBoxItem100);
            this.HexListBox1.Items.Add(hexListBoxItem101);
            this.HexListBox1.Items.Add(hexListBoxItem102);
            this.HexListBox1.Items.Add(hexListBoxItem103);
            this.HexListBox1.Items.Add(hexListBoxItem104);
            this.HexListBox1.Items.Add(hexListBoxItem105);
            this.HexListBox1.Items.Add(hexListBoxItem106);
            this.HexListBox1.Items.Add(hexListBoxItem107);
            this.HexListBox1.Items.Add(hexListBoxItem108);
            this.HexListBox1.Items.Add(hexListBoxItem109);
            this.HexListBox1.Items.Add(hexListBoxItem110);
            this.HexListBox1.Items.Add(hexListBoxItem111);
            this.HexListBox1.Items.Add(hexListBoxItem112);
            this.HexListBox1.Items.Add(hexListBoxItem113);
            this.HexListBox1.Items.Add(hexListBoxItem114);
            this.HexListBox1.Items.Add(hexListBoxItem115);
            this.HexListBox1.Items.Add(hexListBoxItem116);
            this.HexListBox1.Items.Add(hexListBoxItem117);
            this.HexListBox1.Items.Add(hexListBoxItem118);
            this.HexListBox1.Items.Add(hexListBoxItem119);
            this.HexListBox1.Items.Add(hexListBoxItem120);
            this.HexListBox1.Items.Add(hexListBoxItem121);
            this.HexListBox1.Items.Add(hexListBoxItem122);
            this.HexListBox1.Items.Add(hexListBoxItem123);
            this.HexListBox1.Items.Add(hexListBoxItem124);
            this.HexListBox1.Items.Add(hexListBoxItem125);
            this.HexListBox1.Items.Add(hexListBoxItem126);
            this.HexListBox1.Items.Add(hexListBoxItem127);
            this.HexListBox1.Items.Add(hexListBoxItem128);
            this.HexListBox1.Items.Add(hexListBoxItem129);
            this.HexListBox1.Items.Add(hexListBoxItem130);
            this.HexListBox1.Items.Add(hexListBoxItem131);
            this.HexListBox1.Items.Add(hexListBoxItem132);
            this.HexListBox1.Items.Add(hexListBoxItem133);
            this.HexListBox1.Items.Add(hexListBoxItem134);
            this.HexListBox1.Items.Add(hexListBoxItem135);
            this.HexListBox1.Items.Add(hexListBoxItem136);
            this.HexListBox1.Items.Add(hexListBoxItem137);
            this.HexListBox1.Items.Add(hexListBoxItem138);
            this.HexListBox1.Items.Add(hexListBoxItem139);
            this.HexListBox1.Items.Add(hexListBoxItem140);
            this.HexListBox1.Items.Add(hexListBoxItem141);
            this.HexListBox1.Items.Add(hexListBoxItem142);
            this.HexListBox1.Items.Add(hexListBoxItem143);
            this.HexListBox1.Items.Add(hexListBoxItem144);
            this.HexListBox1.Items.Add(hexListBoxItem145);
            this.HexListBox1.Items.Add(hexListBoxItem146);
            this.HexListBox1.Items.Add(hexListBoxItem147);
            this.HexListBox1.Items.Add(hexListBoxItem148);
            this.HexListBox1.Items.Add(hexListBoxItem149);
            this.HexListBox1.Items.Add(hexListBoxItem150);
            this.HexListBox1.Items.Add(hexListBoxItem151);
            this.HexListBox1.Items.Add(hexListBoxItem152);
            this.HexListBox1.Items.Add(hexListBoxItem153);
            this.HexListBox1.Items.Add(hexListBoxItem154);
            this.HexListBox1.Items.Add(hexListBoxItem155);
            this.HexListBox1.Items.Add(hexListBoxItem156);
            this.HexListBox1.Items.Add(hexListBoxItem157);
            this.HexListBox1.Items.Add(hexListBoxItem158);
            this.HexListBox1.Items.Add(hexListBoxItem159);
            this.HexListBox1.Items.Add(hexListBoxItem160);
            this.HexListBox1.Items.Add(hexListBoxItem161);
            this.HexListBox1.Items.Add(hexListBoxItem162);
            this.HexListBox1.Items.Add(hexListBoxItem163);
            this.HexListBox1.Items.Add(hexListBoxItem164);
            this.HexListBox1.Items.Add(hexListBoxItem165);
            this.HexListBox1.Items.Add(hexListBoxItem166);
            this.HexListBox1.Items.Add(hexListBoxItem167);
            this.HexListBox1.Items.Add(hexListBoxItem168);
            this.HexListBox1.Items.Add(hexListBoxItem169);
            this.HexListBox1.Items.Add(hexListBoxItem170);
            this.HexListBox1.Items.Add(hexListBoxItem171);
            this.HexListBox1.Items.Add(hexListBoxItem172);
            this.HexListBox1.Items.Add(hexListBoxItem173);
            this.HexListBox1.Items.Add(hexListBoxItem174);
            this.HexListBox1.Items.Add(hexListBoxItem175);
            this.HexListBox1.Items.Add(hexListBoxItem176);
            this.HexListBox1.Items.Add(hexListBoxItem177);
            this.HexListBox1.Items.Add(hexListBoxItem178);
            this.HexListBox1.Items.Add(hexListBoxItem179);
            this.HexListBox1.Items.Add(hexListBoxItem180);
            this.HexListBox1.Items.Add(hexListBoxItem181);
            this.HexListBox1.Items.Add(hexListBoxItem182);
            this.HexListBox1.Items.Add(hexListBoxItem183);
            this.HexListBox1.Items.Add(hexListBoxItem184);
            this.HexListBox1.Items.Add(hexListBoxItem185);
            this.HexListBox1.Items.Add(hexListBoxItem186);
            this.HexListBox1.Items.Add(hexListBoxItem187);
            this.HexListBox1.Items.Add(hexListBoxItem188);
            this.HexListBox1.Items.Add(hexListBoxItem189);
            this.HexListBox1.Items.Add(hexListBoxItem190);
            this.HexListBox1.Items.Add(hexListBoxItem191);
            this.HexListBox1.Items.Add(hexListBoxItem192);
            this.HexListBox1.Items.Add(hexListBoxItem193);
            this.HexListBox1.Items.Add(hexListBoxItem194);
            this.HexListBox1.Items.Add(hexListBoxItem195);
            this.HexListBox1.Items.Add(hexListBoxItem196);
            this.HexListBox1.Items.Add(hexListBoxItem197);
            this.HexListBox1.Items.Add(hexListBoxItem198);
            this.HexListBox1.Items.Add(hexListBoxItem199);
            this.HexListBox1.Items.Add(hexListBoxItem200);
            this.HexListBox1.Items.Add(hexListBoxItem201);
            this.HexListBox1.Items.Add(hexListBoxItem202);
            this.HexListBox1.Items.Add(hexListBoxItem203);
            this.HexListBox1.Items.Add(hexListBoxItem204);
            this.HexListBox1.Items.Add(hexListBoxItem205);
            this.HexListBox1.Items.Add(hexListBoxItem206);
            this.HexListBox1.Items.Add(hexListBoxItem207);
            this.HexListBox1.Items.Add(hexListBoxItem208);
            this.HexListBox1.Items.Add(hexListBoxItem209);
            this.HexListBox1.Items.Add(hexListBoxItem210);
            this.HexListBox1.Items.Add(hexListBoxItem211);
            this.HexListBox1.Items.Add(hexListBoxItem212);
            this.HexListBox1.Items.Add(hexListBoxItem213);
            this.HexListBox1.Items.Add(hexListBoxItem214);
            this.HexListBox1.Items.Add(hexListBoxItem215);
            this.HexListBox1.Items.Add(hexListBoxItem216);
            this.HexListBox1.Items.Add(hexListBoxItem217);
            this.HexListBox1.Items.Add(hexListBoxItem218);
            this.HexListBox1.Items.Add(hexListBoxItem219);
            this.HexListBox1.Items.Add(hexListBoxItem220);
            this.HexListBox1.Items.Add(hexListBoxItem221);
            this.HexListBox1.Items.Add(hexListBoxItem222);
            this.HexListBox1.Items.Add(hexListBoxItem223);
            this.HexListBox1.Items.Add(hexListBoxItem224);
            this.HexListBox1.Items.Add(hexListBoxItem225);
            this.HexListBox1.Items.Add(hexListBoxItem226);
            this.HexListBox1.Items.Add(hexListBoxItem227);
            this.HexListBox1.Items.Add(hexListBoxItem228);
            this.HexListBox1.Items.Add(hexListBoxItem229);
            this.HexListBox1.Items.Add(hexListBoxItem230);
            this.HexListBox1.Items.Add(hexListBoxItem231);
            this.HexListBox1.Items.Add(hexListBoxItem232);
            this.HexListBox1.Items.Add(hexListBoxItem233);
            this.HexListBox1.Items.Add(hexListBoxItem234);
            this.HexListBox1.Items.Add(hexListBoxItem235);
            this.HexListBox1.Items.Add(hexListBoxItem236);
            this.HexListBox1.Items.Add(hexListBoxItem237);
            this.HexListBox1.Items.Add(hexListBoxItem238);
            this.HexListBox1.Items.Add(hexListBoxItem239);
            this.HexListBox1.Items.Add(hexListBoxItem240);
            this.HexListBox1.Items.Add(hexListBoxItem241);
            this.HexListBox1.Items.Add(hexListBoxItem242);
            this.HexListBox1.Items.Add(hexListBoxItem243);
            this.HexListBox1.Items.Add(hexListBoxItem244);
            this.HexListBox1.Items.Add(hexListBoxItem245);
            this.HexListBox1.Items.Add(hexListBoxItem246);
            this.HexListBox1.Items.Add(hexListBoxItem247);
            this.HexListBox1.Items.Add(hexListBoxItem248);
            this.HexListBox1.Items.Add(hexListBoxItem249);
            this.HexListBox1.Items.Add(hexListBoxItem250);
            this.HexListBox1.Items.Add(hexListBoxItem251);
            this.HexListBox1.Items.Add(hexListBoxItem252);
            this.HexListBox1.Items.Add(hexListBoxItem253);
            this.HexListBox1.Items.Add(hexListBoxItem254);
            this.HexListBox1.Items.Add(hexListBoxItem255);
            this.HexListBox1.Items.Add(hexListBoxItem256);
            this.HexListBox1.Items.Add(hexListBoxItem257);
            this.HexListBox1.Items.Add(hexListBoxItem258);
            this.HexListBox1.Items.Add(hexListBoxItem259);
            this.HexListBox1.Items.Add(hexListBoxItem260);
            this.HexListBox1.Items.Add(hexListBoxItem261);
            this.HexListBox1.Items.Add(hexListBoxItem262);
            this.HexListBox1.Items.Add(hexListBoxItem263);
            this.HexListBox1.Items.Add(hexListBoxItem264);
            this.HexListBox1.Items.Add(hexListBoxItem265);
            this.HexListBox1.Items.Add(hexListBoxItem266);
            this.HexListBox1.Items.Add(hexListBoxItem267);
            this.HexListBox1.Items.Add(hexListBoxItem268);
            this.HexListBox1.Items.Add(hexListBoxItem269);
            this.HexListBox1.Items.Add(hexListBoxItem270);
            this.HexListBox1.Items.Add(hexListBoxItem271);
            this.HexListBox1.Items.Add(hexListBoxItem272);
            this.HexListBox1.Items.Add(hexListBoxItem273);
            this.HexListBox1.Items.Add(hexListBoxItem274);
            this.HexListBox1.Items.Add(hexListBoxItem275);
            this.HexListBox1.Items.Add(hexListBoxItem276);
            this.HexListBox1.Items.Add(hexListBoxItem277);
            this.HexListBox1.Items.Add(hexListBoxItem278);
            this.HexListBox1.Items.Add(hexListBoxItem279);
            this.HexListBox1.Items.Add(hexListBoxItem280);
            this.HexListBox1.Items.Add(hexListBoxItem281);
            this.HexListBox1.Items.Add(hexListBoxItem282);
            this.HexListBox1.Items.Add(hexListBoxItem283);
            this.HexListBox1.Items.Add(hexListBoxItem284);
            this.HexListBox1.Items.Add(hexListBoxItem285);
            this.HexListBox1.Items.Add(hexListBoxItem286);
            this.HexListBox1.Items.Add(hexListBoxItem287);
            this.HexListBox1.Items.Add(hexListBoxItem288);
            this.HexListBox1.Items.Add(hexListBoxItem289);
            this.HexListBox1.Items.Add(hexListBoxItem290);
            this.HexListBox1.Items.Add(hexListBoxItem291);
            this.HexListBox1.Items.Add(hexListBoxItem292);
            this.HexListBox1.Items.Add(hexListBoxItem293);
            this.HexListBox1.Items.Add(hexListBoxItem294);
            this.HexListBox1.Items.Add(hexListBoxItem295);
            this.HexListBox1.Items.Add(hexListBoxItem296);
            this.HexListBox1.Items.Add(hexListBoxItem297);
            this.HexListBox1.Items.Add(hexListBoxItem298);
            this.HexListBox1.Items.Add(hexListBoxItem299);
            this.HexListBox1.Items.Add(hexListBoxItem300);
            this.HexListBox1.Items.Add(hexListBoxItem301);
            this.HexListBox1.Items.Add(hexListBoxItem302);
            this.HexListBox1.Items.Add(hexListBoxItem303);
            this.HexListBox1.Items.Add(hexListBoxItem304);
            this.HexListBox1.Items.Add(hexListBoxItem305);
            this.HexListBox1.Items.Add(hexListBoxItem306);
            this.HexListBox1.Items.Add(hexListBoxItem307);
            this.HexListBox1.Items.Add(hexListBoxItem308);
            this.HexListBox1.Items.Add(hexListBoxItem309);
            this.HexListBox1.Items.Add(hexListBoxItem310);
            this.HexListBox1.Items.Add(hexListBoxItem311);
            this.HexListBox1.Items.Add(hexListBoxItem312);
            this.HexListBox1.Items.Add(hexListBoxItem313);
            this.HexListBox1.Items.Add(hexListBoxItem314);
            this.HexListBox1.Items.Add(hexListBoxItem315);
            this.HexListBox1.Items.Add(hexListBoxItem316);
            this.HexListBox1.Items.Add(hexListBoxItem317);
            this.HexListBox1.Items.Add(hexListBoxItem318);
            this.HexListBox1.Items.Add(hexListBoxItem319);
            this.HexListBox1.Items.Add(hexListBoxItem320);
            this.HexListBox1.Items.Add(hexListBoxItem321);
            this.HexListBox1.Items.Add(hexListBoxItem322);
            this.HexListBox1.Items.Add(hexListBoxItem323);
            this.HexListBox1.Items.Add(hexListBoxItem324);
            this.HexListBox1.Items.Add(hexListBoxItem325);
            this.HexListBox1.Items.Add(hexListBoxItem326);
            this.HexListBox1.Items.Add(hexListBoxItem327);
            this.HexListBox1.Items.Add(hexListBoxItem328);
            this.HexListBox1.Items.Add(hexListBoxItem329);
            this.HexListBox1.Items.Add(hexListBoxItem330);
            this.HexListBox1.Items.Add(hexListBoxItem331);
            this.HexListBox1.Items.Add(hexListBoxItem332);
            this.HexListBox1.Items.Add(hexListBoxItem333);
            this.HexListBox1.Items.Add(hexListBoxItem334);
            this.HexListBox1.Items.Add(hexListBoxItem335);
            this.HexListBox1.Items.Add(hexListBoxItem336);
            this.HexListBox1.Items.Add(hexListBoxItem337);
            this.HexListBox1.Items.Add(hexListBoxItem338);
            this.HexListBox1.Items.Add(hexListBoxItem339);
            this.HexListBox1.Items.Add(hexListBoxItem340);
            this.HexListBox1.Items.Add(hexListBoxItem341);
            this.HexListBox1.Items.Add(hexListBoxItem342);
            this.HexListBox1.Items.Add(hexListBoxItem343);
            this.HexListBox1.Items.Add(hexListBoxItem344);
            this.HexListBox1.Items.Add(hexListBoxItem345);
            this.HexListBox1.Items.Add(hexListBoxItem346);
            this.HexListBox1.Items.Add(hexListBoxItem347);
            this.HexListBox1.Items.Add(hexListBoxItem348);
            this.HexListBox1.Items.Add(hexListBoxItem349);
            this.HexListBox1.Items.Add(hexListBoxItem350);
            this.HexListBox1.Items.Add(hexListBoxItem351);
            this.HexListBox1.Items.Add(hexListBoxItem352);
            this.HexListBox1.Items.Add(hexListBoxItem353);
            this.HexListBox1.Items.Add(hexListBoxItem354);
            this.HexListBox1.Items.Add(hexListBoxItem355);
            this.HexListBox1.Items.Add(hexListBoxItem356);
            this.HexListBox1.Items.Add(hexListBoxItem357);
            this.HexListBox1.Items.Add(hexListBoxItem358);
            this.HexListBox1.Items.Add(hexListBoxItem359);
            this.HexListBox1.Items.Add(hexListBoxItem360);
            this.HexListBox1.Items.Add(hexListBoxItem361);
            this.HexListBox1.Items.Add(hexListBoxItem362);
            this.HexListBox1.Items.Add(hexListBoxItem363);
            this.HexListBox1.Items.Add(hexListBoxItem364);
            this.HexListBox1.Items.Add(hexListBoxItem365);
            this.HexListBox1.Items.Add(hexListBoxItem366);
            this.HexListBox1.Location = new System.Drawing.Point(16, 17);
            this.HexListBox1.Margin = new System.Windows.Forms.Padding(4);
            this.HexListBox1.Name = "HexListBox1";
            this.HexListBox1.SelectedItem = hexListBoxItem1;
            this.HexListBox1.Size = new System.Drawing.Size(232, 550);
            this.HexListBox1.TabIndex = 18;
            // 
            // Text_Game
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.BasicListBoxAssociate1);
            this.Controls.Add(this.HexListBox1);
            this.Margin = new System.Windows.Forms.Padding(4);
            this.Name = "Text_Game";
            this.Size = new System.Drawing.Size(787, 603);
            this.BasicListBoxAssociate1.ResumeLayout(false);
            this.BasicListBoxAssociate1.PerformLayout();
            this.ResumeLayout(false);

        }

        internal BasicTools.BasicControls.BasicListBoxAssociate BasicListBoxAssociate1;
        internal HexTools.HexListBox HexListBox1;
        internal HexTools.HexMessageBox MessageBox;
    }
}